import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./layouts/navbar/Navbar";
import Header from "./layouts/header/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nex coating",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className=" flex min-h-screen flex-col items-center justify-between p-24">
          {children}
        </main>
      </body>
    </html>
  );
}
