import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./layouts/navbar/Navbar";
import Header from "./layouts/header/page";
const inter = Inter({ subsets: ["latin"] });
import Footer from "./layouts/footer.tsx";
export const metadata = {
  title: "Nex coating",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="min-h-[94vh] pt-16 text-center">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
