import MainPage from "./mainPage";
import "./globals.css";
import Navbar from "./layouts/navbar/Navbar";
import Header from "./layouts/header/page";
import Footer from "./layouts/footer.tsx";

export const metadata = {
  title: "Nex coating",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <MainPage />
    </>
  );
}
